# Generated by Django 4.1 on 2022-09-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sernder_Details',
            new_name='Booking_Details',
        ),
    ]
