# Generated by Django 4.1 on 2022-09-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_sernder_details_booking_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=400)),
                ('destination', models.CharField(max_length=400)),
                ('shipment_mode', models.CharField(max_length=400)),
                ('shipment_date', models.DateField()),
                ('time_updated', models.TimeField()),
                ('location', models.CharField(max_length=400)),
                ('updated_by', models.CharField(max_length=400)),
                ('remarks', models.CharField(max_length=400)),
            ],
        ),
    ]
